mqtt:
  broker: ssl://eu1.cloud.thethings.network:8883
  clientId: mqtt-client-1234
  username: 79857987987@ttn
  applicationId: 79857987987
  password: NNSXS.E5QCXWMGCN5VAD3UEHS7PMTNPD53UFZDL6UIYAI.VGK527VFF6R3IMOONYUQ73FXWO7ASIHKETXS5QZEEQPK7DN6VBBA
  subscribeTopic: v3/79857987987@ttn/devices/+/up
  publishTopic: v3/79857987987@ttn/devices/goodname/down/push
